language: php
dist: trusty

php:
- '5.4'
- '5.5'
- '5.6'
- '7.0'
- '7.1'
- '7.2'

before_script:
- if find . -name "*.php" -exec php -l {} 2>&1 \; | grep -iv "no syntax errors detected"; then exit 1; fi

script: true

install: true

notifications:
  email:
    on_success: change
    on_failure: always
    recipients:
    - developers@cacti.net
  slack:
    secure: 7/tstBOYPqEiajNGGD9t5N9BMr8mO+JYlxH91cJ5ZfFYd+7tKm4CiOZv3WwPUY0o/TiG0tce2tFfaeIVMGXp9j4MuqosQBKQBdp+Hwf9WZCK5juWc8L3aIITa+AQzkuk28wefTZdIKth3M6B+JoFPU7PaGoUPq+r95en2CU8RnmooU8vGLnK2/0o9MWEbXNOotuFSvsQ1aWiMIuQIBrNzIjE56ew11XsdJDcTsjIq0E5hEqmHbeQXJ9H0jTMMoqz8rd5i9wfTTwuuSYZKelijOR0mj8masrEXmFWbFY5/MVlcr9DWcVumwgZaxs0k+Wt+d3JRqOUIADCLxBMrWhPVFbugkU3EsoFlAiD4e+OJWm4k1ZM4iQMOCDUheN9SDXJ8AdB9zC7KciAfNGdW+0tiHHzwxe6W0eGtEf5/G4/0c6QRIHZzS24SWGUCBgYQsz7XGaxDl48O1HIdwDIh050dis22EhFb0VLnzNWBfy00uSsOzndPIbd1YPL1shAq4AyOiJkxpSfTE0gImvVU91ZzNq1UhD6egal/Mt3j3Z9Xecc5A6Fz0dtShUbDrsU2NvTDLRKBqQcmdM9J9OUpV/ZVTeW9lZChu7ZRypNtrE/LUpzmBLAlfTzQ2hSuwwOCivQ4Yz8jj/WE9Lunb5Mg7vWnw2Zg4zjWpkY87Q+16pV9GQ=
